### ISSUE TITLE
Compatibility with ES6 module export 

### ISSUE THREAD

**Issue by yairEO** [shipshapecode/tether#136]
I would be nice to have an Automated build which will generate "version" of Tether.js, like AMD, UMD, commonJS and ES6 export module, which one could import. 

Currently the Tether.js file mixes code which might not even be used, and it seems like a good idea to auto-generate these files automatically and push them to GIT once a version is released, some a dev could choose which "port" to use.

**Comment by FezVrasta** [comment]
+1

**Comment by souporserious** [comment]
+1

**Comment by jrgleason** [comment]
Has anyone attempted to implement anything themselves?

**Comment by kopax** [comment]
It's now possible to make a module for everyone using rollup. I had some issue using tether in webpack because I use it inside an es module.

I had the error "extend is not defined" I think because [here](https://github.com/HubSpot/tether/blob/master/src/js/tether.js#L809)

I have tried the recommendation here : 

- https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports
- https://github.com/rollup/rollup-plugin-node-resolve

It seems hard to import tether and I am thinking to do a PR so we can have them all. However, I am not able to test it for every environment. Anyone interested to work with me?

**Comment by rwwagner90** [comment]
We now export both a tether.esm.js and tether.js, so importing as a module should work. Would anyone like to try it out?

**Comment by m-nab** [comment]
@rwwagner90 It works when using tether@next.
