### ISSUE TITLE
Clean up on destroy

### ISSUE THREAD

**Issue by jonathantyates** [shipshapecode/tether#36]
Currently when a tether is destroyed, the element retains its classes, styles, and DOM manipulation.  I would expect these changes would be returned to their original states on destroy.

**Comment by sjelfull** [comment]
I feel destroy should clean up fully. That also means returning them to their rightful place in the DOM. Alternatively, an option might be to clone them instead of move them in the DOM. I don't know if that is a good idea, but that's another discussion (?).

**The use case:**
I'm toggling Tether on certain breakpoints. On mobile, the elements is just in a list, on desktop I use Tether to position them.

**Comment by yairEO** [comment]
:+1: 

Even `disable` should clean up properly! this is so **annoying**, I have to save the original classname and then restore it, and If it ever get changed in real-time somewhere un-related to Tether this method won't work.

There should be at least a `clean` method for Tether to cleanup whatever class it added manually.

**Comment by yairEO** [comment]
Personally I use this [jQuery.removeClassPrefix.js](https://gist.github.com/yairEO/3441db0dea7e37da49e930f21a2a5b64) to cleanup **tether** classes on the _target_

    $target.removeClassPrefix('tether');

**Comment by SirLamer** [comment]
+1

I am trying to use Tether in an environment without using jQuery, which makes this even more annoying.

**Comment by yairEO** [comment]
@SirLamer - this is why i'm against anything other than jQuery. 
it creates a complete MESS on the internet where you have people code for very very specific way of work which is completely incompatible with anything else. I never ever write anything which is not compatible for any project, at all, but many people write React component, Angular directives and Vue-whatever and then others cannot use it! worthless... so so sad.
jQuery is the norm and all the others do exactly what it does, only with different method names... to me it's sad. and i'm a web developer since the 90s, seeing what it has become.. sad.

**Comment by SirLamer** [comment]
Lol okay, well to your granddaddy Fortran was the norm so let's have everyone use that and never change and everything will be more awesome.

P.S. The state of the art in the 1990's was GeoCities. But yeah you're right that's a way better product than Facebook.

**Comment by yairEO** [comment]
@SirLamer - you missed the point, which is never to create a locked-in solution, even if it seems better. 
all these "new" things are creating massive amounts of code from the community which cannot be used cross-platform (for example, a React person cannot use an angular-written piece of code) and from my years of experience I've seen many things come and go, and I've told people Angular would die, when it was in its peak. and it did die. people are flooding the internet with future-useless code which nobody else can use but inside their own dying community. Vue will die as well, be sure of it. everything dies but jQuery, because it is so basic, and flexible, it is literally ageless.

I am against locked-in code, and I've said so many times in the Flash community in the end of 2008. I left Flash because I saw then how a locked-in env, however powerful, is false.

**Comment by sjelfull** [comment]
@yairEO Your forgetting: jQuery is itself a lock-in. JavaScript is relatively ageless, jQuery is not. jQuery-specific solutions is these days a no-go for me.

**Comment by SirLamer** [comment]
Software is iterative, new stuff is built using old stuff as a base, the new hotness will always be changing, that's inherent in the gig.

Even within Javascript things change, and that's good. Do you systematically not use JS Promises?

**Comment by zackbloom** [comment]
@yairEO youmightnotneedjquery.com, and that was as of 2014. Browsers are much more compatible now than they were when jQuery was created. When you talk about Vue or React, you are talking about a layer higher than actually interacting with the DOM, Promises, and the other features jQuery provides. Essentially all of those things are now built directly into browsers in a compatible way, why would you need any library at all to use them?
