### ISSUE TITLE
Tether is harder to update due to a missing changelog

### ISSUE THREAD

**Issue by EamonNerbonne** [shipshapecode/tether#40]
I started using tether (which works brilliantly btw - thanks!) at version 0.5.2, and will update to 0.6.4 today.

However, that's hard to do because it's unclear what has changed since then (the commit history shows this is mostly documentation a few bugfixes).

A short changelog would be really helpful to clarify what aspects of an upgrade might need attention (which if I understand correctly is likely to be not much for 0.5.2 -> 0.6.4).

**Comment by NicBright** [comment]
+1

**Comment by AsaAyers** [comment]
@geekjuice I don't know who owns the project but you tagged the last release. This issue is over a year old. Can we either get a changelog or close it with a clear "No, we're not going to provide a changelog"?

For anyone adventerous enough to try to look through the code you can use `/compare/` to look through changes: https://github.com/HubSpot/tether/compare/v0.6.5...v0.7.2

Also, do you follow semver? Does v0.7 introduce some breaking change I should know about before I try this upgrade?

**Comment by geekjuice** [comment]
@AsaAyers I've actually been working on all `tether` related projects with `tether` being the final one. If you check projects like [tooltip](https://github.com/HubSpot/tooltip/blob/master/CHANGELOG.md), [drop](https://github.com/HubSpot/drop/blob/master/CHANGELOG.md), [select](https://github.com/HubSpot/select/blob/master/CHANGELOG.md), & [shepherd](https://github.com/HubSpot/tooltip/blob/master/CHANGELOG.md), I've started to add changelogs.

In regards to semver, out [contributing doc](https://github.com/HubSpot/tooltip/blob/master/CONTRIBUTING.md) tried to highlight how we will start dealing with versioning. The basic gist is:

- __None__: Documentation updates
- __Patch__: Bug fixes
- __Minor__: Non-breaking feature added
- __Major__: Anything not backwards compatible from the current version

As far as `v0.7`, it doesn't seem like there is anything breaking and rather a few features were added. However, I wouldn't consider this project to follow semver quite yet, but hopefully in the upcoming update, it should.

Hope that helps and let me know if you have any other questions :+1:

**Comment by AsaAyers** [comment]
:+1: Thanks for the quick update.

**Comment by rwwagner90** [comment]
We will be generating changelogs going forward.
